### ISSUE TITLE
Duplicate single quotes causes mysql to throw error

### ISSUE THREAD

**Issue by ghost** [n8barr/automotive-model-year-data#2]
Line 1127 and line 1469 both have duplicate single quotes that cause mysql to throw an error. Thanks for this database by the way. Sweeeeeeet!
![Untitled](https://f.cloud.github.com/assets/3111605/144112/354332fe-73ef-11e2-8aa1-310bcba16032.png)

**Comment by n8barr** [comment]
Fixed this with commit a691da48f2667c908f53bc2e5c28265dbf4a5984
