### ISSUE TITLE
Some odd Makes

### ISSUE THREAD

**Issue by infernocloud** [n8barr/automotive-model-year-data#6]
These are on models as separate Makes from "BMW"
BMW 745,BMW
BMW X5,BMW
BMW Z4,BMW
BMW,BMW
BMW,BMW Z4

I'm not very familiar with automobile data, but is this just a data error?

**Comment by infernocloud** [comment]
Here are some other ones that could benefit from consolidation. I would have just adjusted them and submitted a pull request, but I'm not sure if some of them are intentional for some reason.

Chrysler
Chrysler Group LLC

Ford
Ford Motor Company

Lamborghini
Lamborghini,Coupé

Mazda
Mazda,Mazda MX-6

Mitsubishi
Mitsubishi Motors
Mitsubishi,Mitsubishi

Porsche
Porsche,Mitsubishi

Suzuki
Suzuki Motor Corporation

**Comment by forresti** [comment]
Along the same lines: 
Lotus and Lotus Cars

Perhaps one of us should just find/replace these fixes and then do a pull request.

**Comment by infernocloud** [comment]
Yeah I fixed them all within my MySQL database, but for some reason
HeidiSQL won't export in the same format as this repo has the data...
Really silly.
